### ISSUE TITLE
No logging when content of a field is empty

### ISSUE THREAD

**Issue by bertoost** [argnist/fastField#1]
For example I do: [[#10.introtext]]
This field is empty as in NULL. Because in model/fastfield/fastfield.php contains a check "if(is_null(..))", the error "fastField: unknown field `introtext`" is logged. The field exists, but the content is empty.

Think you should do before:

<pre>$fields = $this->modx->getFields('modResource');</pre>

And change the if statement into

<pre>if(!array_key_exists($tag[1], $fields)) { /* logging error here */ }</pre>

This way it realy not exists!
See http://rtfm.modx.com/display/xPDO20/xPDO.getFields

For TV values I think you should not report errors. There isn't a way to check if the resource has the wanted TV at all, so to avoid load issues, just return an empty string. People can work with output filters if there isn't a value returned in the template/chunk.

This all because, when you use it a lot the error-log can be huge, and it isn't a problem as far I can see.

**Comment by argnist** [comment]
Fixed. As it turned out $resource->_fields is 10000 times faster than $modx->getFields() :).
