### ISSUE TITLE
[Question] How do I get the Articles container title?

### ISSUE THREAD

**Issue by greyskymedia** [argnist/fastField#2]
I just haven't a clue... thanks!

**Comment by argnist** [comment]
In article resource for example: [[#[[*parent]].pagetitle]]

**Comment by greyskymedia** [comment]
I'm trying to get the articles wrapper page title, I'll try that tomorrow, thanks!!

Jamison Mergens
916.234.0040

On Sep 17, 2013, at 6:45 PM, argnist notifications@github.com wrote:

In article resource for example: [[#[[*parent]].pagetitle]]

**Comment by argnist** [comment]
In chunk it may be [[#[[+parent]].pagetitle]]

**Comment by greyskymedia** [comment]
neither worked... it's ok, i'll just hard code it, thanks though
