### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by bertoost** [argnist/fastField#3]
I used it in one of my projects. It is very very slow loading pages. When I removed it, page load (uncached) is reduced tremendously (at least with 20 seconds).

**Comment by argnist** [comment]
It seems you used version under 1.3.0, don't you? After 1.3.0 there is very different approach how the component works. By the way I used old versions on many websites and didn't see so huge reducing of page load. 0.1-0.2 s but not 20.

**Comment by bertoost** [comment]
It can be.. I immediately removed it because of performance issues.
Maybe alos because of some other packages.. I don't know of course.
