### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by bezumkin** [argnist/fastField#5]
<a href="https://github.com/bezumkin/pdoTools/commit/7b865434e375ecf4dfefb10237a49b2ad909d5bd">Добавляю свой парсер в pdoTools</a> для более быстрой обработки простых тегов MODX.

Пока неясно, есть выгода, или нет, но в любом случае так оптимальнее код. 

Отсюда вопрос, ты не против, если я добавлю к себе функционал работы с твоими тегами [[#15.pagetitle]]? Конечно, сам код я перепишу на pdo.

Это очень полезная штука, особенно вывод данных их $_POST и $_SESSION.

**Comment by argnist** [comment]
Буду не против, если упомянешь как либо меня и Dimlight Studio (
http://dimlight.ru). Получается тогда развивать fastField мне уже смысла не
будет. Я еще хотел добавить возможность из любого класса получать поле, но
не успел придумать синтаксис.

17 декабря 2013 г., 13:43 пользователь Vasily Naumkin <
notifications@github.com> написал:

> Добавляю свой парсер в pdoToolshttps://github.com/bezumkin/pdoTools/commit/7b865434e375ecf4dfefb10237a49b2ad909d5bdдля более быстрой обработки простых тегов MODX.
> 
> Пока неясно, есть выгода, или нет, но в любом случае так оптимальнее код.
> 
> Отсюда вопрос, ты не против, если я добавлю к себе функционал работы с
> твоими тегами [[#15.pagetitle]]? Конечно, сам код я перепишу на pdo.
> 
> Это очень полезная штука, особенно вывод данных их $_POST и $_SESSION.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/argnist/fastField/issues/5
> .

## 

С уважением, Киреев Виталий kireevvit@gmail.com

**Comment by bezumkin** [comment]
Конечно упомяну, как автора отличной идеи!

Быстро получать документы pdoTools и так умеет и с подключением ТВ и ограничением выборки полей. 

Плюс есть сниппет pdoField, который тоже что угодно достанет. В общем-то, я и хочу продублировать его фунционал в парсер.

Спасибо за разрешение =)

**Comment by bezumkin** [comment]
Добавил вот так https://github.com/bezumkin/pdoTools/commit/b905b7cd2a8586769bc268503d63c14165634744

Из отличий - минимум использования объектов и возможность распечатки массивов целиком.
